### ISSUE TITLE
SPIKE: What will be the best backend framework for our job

### ISSUE THREAD

**Issue by Hreherch** [cmput401-fall2018/virtual-outdoors-club#6]
- [x] Decide best framework
- [x] Get it running on cybera

**Comment by hiufungk** [comment]
backend framework: PostgreSQL and Django

**Comment by hiufungk** [comment]
> 
> 
>     * [x]  Decide best framework
> 
>     * [x]  Get it running on cybera

**Comment by Hreherch** [comment]
@dong-alex @hiufungk add the question and the answer/research you guys did to https://github.com/cmput401-fall2018/virtual-outdoors-club/wiki/Questions-and-Answers and then you can close this :)

**Comment by dong-alex** [comment]
Q&A has been updated with details in regards to this question.
